name: Fetch Webpage Content and Save
on:
  push:
    branches:
      - main  # 可以根据你的需求修改触发工作流的分支，这里以 main 分支为例

jobs:
  fetch_and_save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install required packages
        run: |
          python -m pip install --upgrade pip
          pip install requests  # 安装 requests 库用于获取网页内容

      - name: Fetch webpage content
        run: |
          import requests
          url = "https://6666.fangfang36006-47a.workers.dev/"  # 请替换为你实际要获取内容的网页 URL
          response = requests.get(url)
          if response.status_code == 200:
              with open('test.txt', 'w', encoding='utf-8') as file:
                  file.write(response.text)
          else:
              print(f"Failed to fetch the page. Status code: {response.status_code}")

      - name: Commit and push changes
        run: |
          git config --local user.email "your_email@example.com"  # 请替换为你的邮箱
          git config --local user.name "Your Name"  # 请替换为你的名字
          git add test.txt
          git commit -m "Save webpage content to test.txt" || true  # 防止无变更时提交失败
          git push
